"""Add index to Plan Name fields

Revision ID: c1bf5dbbdfba
Revises: 41642e3152e0
Create Date: 2020-12-25 15:20:06.087421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1bf5dbbdfba'
down_revision = '41642e3152e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_plans_plan_name'), 'plans', ['plan_name'], unique=True)
    op.create_unique_constraint(op.f('uq_plans_id'), 'plans', ['id'])
    op.drop_constraint('uq_plans_plan_name', 'plans', type_='unique')
    op.create_unique_constraint(op.f('uq_user_id'), 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_id'), 'user', type_='unique')
    op.create_unique_constraint('uq_plans_plan_name', 'plans', ['plan_name'])
    op.drop_constraint(op.f('uq_plans_id'), 'plans', type_='unique')
    op.drop_index(op.f('ix_plans_plan_name'), table_name='plans')
    # ### end Alembic commands ###
